### ISSUE TITLE
Opcode "0xf6"

### ISSUE THREAD

**Issue by Haniamin90** [P1sec/hermes-dec#2]
![image](https://user-images.githubusercontent.com/107732507/219130292-348a3ea6-89de-4d17-98b3-7a07430e1f06.png)

**Comment by p1-mmr** [comment]
Hello,

Can your please share your sample .HBC file on this issue, or at ![image](https://user-images.githubusercontent.com/26739350/219876243-4cc6e6db-e2b5-474d-b822-45167b133539.png) if you wish to keep it private?

Thank you!

**Comment by Haniamin90** [comment]
Hello,

bundle sent to mentioned email.

Thanks

**Comment by p1-mmr** [comment]
Hello,

Your sample was produced using a development version of the React Native framework, as it seems to present bytecode version 85.

React Native produced bytecode files bearing version 85 on two occasions, in July 2021 but this version code was left only for a few hours (https://github.com/facebook/hermes/commit/1cc6e722ea9dd9f53def90bb88fbefeca99739b9) before being incremented (https://github.com/facebook/hermes/commit/c4f2fc3f499f7891958b9e6d7ab39fcb6ead93c8) and decremented back (https://github.com/facebook/hermes/commit/1921644140739fedf6382fac1279036d11c4e931), and in March 2022 (https://github.com/facebook/hermes/commit/b74eb2d5bff8ffbfa6914746261c4efd2c4223c5) where it stayed for three months (https://github.com/facebook/hermes/commit/b8235156c0bfb0eea550243e67c5018661ff3185).

I think that I should adapt hermes-dec for supporting the most recent intermediary versions of the Hermes bytecode in order to provide the ability of analyzing certain applications produced using development versions of React Native. I should look at this soon.

Regards,
