### ISSUE TITLE
SHA1 AssertionError

### ISSUE THREAD

**Issue by ScientiaEtVeritas** [P1sec/hermes-dec#4]
I've run `~/hermes-dec/parsers/hbc_file_parser.py file.js.hbc` and it seems, it always returns the following error

```py
  File "~/hermes-dec/parsers/hbc_file_parser.py", line 807, in <module>
    hbc_reader.read_whole_file(file_descriptor)
  File "~/hermes-dec/parsers/hbc_file_parser.py", line 763, in read_whole_file
    self.read_header_from_buffer() # Defines self.header
  File "~/hermes-dec/parsers/hbc_file_parser.py", line 488, in read_header_from_buffer
    assert sha1(file_data[:-SHA1_NUM_BYTES]).digest() == file_data[-SHA1_NUM_BYTES:]
AssertionError
```

- `find` confirms it is `Hermes JavaScript bytecode, version 90`.
- I'm on Python 3.10.5.

**Comment by p1-mmr** [comment]
Hello, 

Thank you for reporting. I am not encountering this error with my development version of Hermes. Can you please share your sample at ![](https://user-images.githubusercontent.com/26739350/219876243-4cc6e6db-e2b5-474d-b822-45167b133539.png) or on this issue? 

Thank you!

**Comment by ScientiaEtVeritas** [comment]
I have sent the sample in question to the mentioned address (using WeTransfer).

**Comment by p1-mmr** [comment]
Should be fixed now, thanks! 

Your file contained a non-standard trailer byte string (`{"bundle_type":"rn-hbc"}\x00`). This should now be ignored through using the file size present in the bytecode file header instead of the actual disk size of the file in order to determine the position of the file footer containing the SHA-1 file hash.
